const type ={
    ADD_DUSHBOARD: 'dushboard/ADD',
    ERROR: 'dushboard/ERROR',
    REQUEST_GAME_SETTINGS: "dushboard/REQUEST_GAME_SETTINGS",
    SUCCESS_GAME_SETTINGS: 'dushboard/SUCCESS_GAME_SETTINGS',
    START_RANDOM_COLOR: 'dushboard/START_RANDOM_COLOR',
    CHANGE_COLOR: 'dushboard/CHANGE_COLOR',
    USER_COLOR:'dushboard/USER_COLOR',
    USER_GAME_SETTINGS: 'dushboard/USER_GAME_SETTINGS',
    USER_INCREMENT: 'dushboard/USER_INCREMENT',
    COMPUTER_INCREMENT: 'dushboard/COMPUTER_INCREMENT',
    CLEAR_RESULT:"dushboard/CLEAR_RESULT",
    USER_ADD: "dushboard/SUCCESS_USER_ADD",
    REQUEST_WINNER_ADD:"dushboard/REQUEST_USER_ADD",
    SUCCESS_WINNER_ADD:"dushboard/SUCCESS_WINNER_ADD",
    REQUEST_ALL_WINNERS: 'dushboard/REQUEST_ALL_WINNERS',
    SUCCESS_ALL_WINNERS: 'dushboard/SUCCESS_ALL_WINNERS'
}
export default type;